os: linux
language: shell

services:
  - docker

addons:
  apt:
    packages:
    - jq

env:
  - ADDON=flicd ARCH=armhf
  - ADDON=flicd ARCH=amd64
  - ADDON=flicd ARCH=i386
  - ADDON=picamera ARCH=armhf
  - ADDON=picamera ARCH=aarch64
  - ADDON=pilight ARCH=armhf
  - ADDON=pilight ARCH=amd64
  - ADDON=pilight ARCH=i386
  - ADDON=zabbix-agent ARCH=armhf
  - ADDON=zabbix-agent ARCH=aarch64
  - ADDON=zabbix-agent ARCH=amd64
  - ADDON=zabbix-agent ARCH=i386

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./build.sh "$ADDON" "$ARCH"

# vim: set ft=yaml et ts=2 sw=2 :
